### ISSUE TITLE
Search does not return results.

### ISSUE THREAD

**Issue by dlfreriks** [johsund/QlikSocial#2]
![image](https://cloud.githubusercontent.com/assets/18123857/16968256/8c207c2a-4dc2-11e6-943d-86f2a3dea648.png)

Search does not return results.

**Comment by johsund** [comment]
Hi dlfreriks,

Are you getting a qlikTicket value in your URL?

Does anything happen when you click the Search button? 
Are you getting a popup with a progress bar?
Do you eventually get moved to a page called Analytics.html?

Cheers,
Johannes

**Comment by dlfreriks** [comment]
Hi,

Attached a video -- nothing happens after the Search button is pushed.  Are there files I need to NPM into node?

**Comment by dlfreriks** [comment]
Link to video:   https://qlik-pe.box.com/s/5qsndzkaqhsi3dqy4ujacp1ssuyfly7u

**Comment by dlfreriks** [comment]
Put an update in github ---  I'd  love to get this running!

Dave Freriks | Emerging Technology Evangelist | PE/DR Team

On Jul 19, 2016, at 19:28, johsund <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi dlfreriks,

Are you getting a qlikTicket value in your URL?

Does anything happen when you click the Search button?
Are you getting a popup with a progress bar?
Do you eventually get moved to a page called Analytics.html?

Cheers,
Johannes

**Comment by dlfreriks** [comment]
Got it to work!  Thanks Johsund!

I was using "workgroup" instead of computer name in the userdirectory setting in config.js

//Configure paths & user info here
config.qlik.hostname = 'win-gsch9gt7omj';
config.qlik.virtualproxy = 'ticket';
config.qlik.userdirectory = 'win-gsch9gt7omj';
config.qlik.username = 'qvadmin';
config.qlik.certificatepath = '';
